modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPL-3.0-only"
[[mods]]
modId = "patpatpat"
version = "${file.jarVersion}"
displayName = "PatPatPat"
authors = "Tapio"
credits = "Thanks to Buuz135's Cat Jammies Mod"
description = ""