modLoader = "javafml"
loaderVersion = "[40,)"
license = "GPL-3.0-only"
[[mods]]
modId = "patpatpat"
version = "${file.jarVersion}"
displayName = "PatPatPat"
authors = "Tapio"
description = "Pat your pets!"